=== es-hs/mock-json/schemas/builder.json
{
  "$ref": "#/definitions/Builder",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Builder": {
      "properties": {
        "childrens": {
          "items": {
            "$ref": "#/definitions/Builder"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "settings": {
          "additionalProperties": {},
          "type": "object"
        },
        "tag": {
          "type": "string"
        },
        "type": {
          "enum": ["component", "section"],
          "type": "string"
        },
        "uid": {
          "type": "string"
        }
      },
      "required": ["tag", "uid"],
      "type": "object"
    }
  }
}

=== es-hs/mock-json/template/section-02.json
{
  "uid": "section-02",
  "tag": "Row",
  "settings": {
    "responsive": {
      "desktop": "repeat(2, minmax(0, 1fr))",
      "tablet": "100%",
      "mobile": "100%"
    }
  },
  "childrens": [
    {
      "uid": "1",
      "tag": "Col",
      "settings": {},
      "childrens": [
        {
          "uid": "4",
          "tag": "Button",
          "settings": {
            "label": "Button"
          }
        }
      ]
    },
    {
      "uid": "2",
      "tag": "Col",
      "settings": {},
      "childrens": [
        {
          "uid": "3",
          "tag": "Button",
          "settings": {
            "label": "Button"
          }
        }
      ]
    }
  ]
}
